# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --export-options-plist exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
