// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD54IY6_51IhIhnPSyxhdkqpVDRb_VkazU',
    appId: '1:814873659197:web:dacde07332997eb0eaa754',
    messagingSenderId: '814873659197',
    projectId: 'cgcc-5f90c',
    authDomain: 'cgcc-5f90c.firebaseapp.com',
    storageBucket: 'cgcc-5f90c.firebasestorage.app',
    measurementId: 'G-8S3X7PYLCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7BAmBYb0mynrB0NaxIPGKRSJIjRLX8Lc',
    appId: '1:814873659197:android:82c2b52622f96a62eaa754',
    messagingSenderId: '814873659197',
    projectId: 'cgcc-5f90c',
    storageBucket: 'cgcc-5f90c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzg5s92HbZfpPSjFVGYLm_TMufX6t1Q60',
    appId: '1:814873659197:ios:3767a70974ba7952eaa754',
    messagingSenderId: '814873659197',
    projectId: 'cgcc-5f90c',
    storageBucket: 'cgcc-5f90c.firebasestorage.app',
    iosBundleId: 'com.example.myFullApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzg5s92HbZfpPSjFVGYLm_TMufX6t1Q60',
    appId: '1:814873659197:ios:3767a70974ba7952eaa754',
    messagingSenderId: '814873659197',
    projectId: 'cgcc-5f90c',
    storageBucket: 'cgcc-5f90c.firebasestorage.app',
    iosBundleId: 'com.example.myFullApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD54IY6_51IhIhnPSyxhdkqpVDRb_VkazU',
    appId: '1:814873659197:web:9b708496513f97f1eaa754',
    messagingSenderId: '814873659197',
    projectId: 'cgcc-5f90c',
    authDomain: 'cgcc-5f90c.firebaseapp.com',
    storageBucket: 'cgcc-5f90c.firebasestorage.app',
    measurementId: 'G-TJ4G2F7QSN',
  );
}
